[2024-06-17T18:18:21.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T18:18:21.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_etl_dag.preprocess_data_pyspark_task manual__2024-06-17T18:17:33.894590+00:00 [queued]>
[2024-06-17T18:18:21.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_etl_dag.preprocess_data_pyspark_task manual__2024-06-17T18:17:33.894590+00:00 [queued]>
[2024-06-17T18:18:21.999+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T18:18:22.034+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data_pyspark_task> on 2024-06-17 18:17:33.894590+00:00
[2024-06-17T18:18:22.041+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_etl_dag', 'preprocess_data_pyspark_task', 'manual__2024-06-17T18:17:33.894590+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmp3wtlsri0']
[2024-06-17T18:18:22.043+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask preprocess_data_pyspark_task
[2024-06-17T18:18:22.047+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T18:18:22.048+0000] {standard_task_runner.py:63} INFO - Started process 1175 to run task
[2024-06-17T18:18:22.125+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_etl_dag.preprocess_data_pyspark_task manual__2024-06-17T18:17:33.894590+00:00 [running]> on host e1be22a1c874
[2024-06-17T18:18:22.368+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_etl_dag' AIRFLOW_CTX_TASK_ID='preprocess_data_pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T18:17:33.894590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T18:17:33.894590+00:00'
[2024-06-17T18:18:22.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T18:18:26.252+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T18:18:26.253+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/youtube_etl_dag.py", line 101, in preprocess_data_pyspark_job
    df = spark.read.csv('/opt/airflow/Youtube-Trending-Data-Raw.csv', header=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 740, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/Youtube-Trending-Data-Raw.csv.
[2024-06-17T18:18:26.293+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_etl_dag, task_id=preprocess_data_pyspark_task, run_id=manual__2024-06-17T18:17:33.894590+00:00, execution_date=20240617T181733, start_date=20240617T181821, end_date=20240617T181826
[2024-06-17T18:18:26.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task preprocess_data_pyspark_task ([PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/Youtube-Trending-Data-Raw.csv.; 1175)
[2024-06-17T18:18:26.362+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T18:18:26.384+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T18:18:26.386+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
